//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFramework {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Settings")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://auto-qa.cubictelecom.com/")]
        public string BaseURL {
            get {
                return ((string)(this["BaseURL"]));
            }
            set {
                this["BaseURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("david.organ@cubictelecom.com")]
        public string User {
            get {
                return ((string)(this["User"]));
            }
            set {
                this["User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cubic!!04")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-09-18")]
        public global::System.DateTime CurrentDate {
            get {
                return ((global::System.DateTime)(this["CurrentDate"]));
            }
            set {
                this["CurrentDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://auto-dev.cubictelecom.com/")]
        public string DevBaseURL {
            get {
                return ((string)(this["DevBaseURL"]));
            }
            set {
                this["DevBaseURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\ChromeDriver")]
        public string ChromeLocation {
            get {
                return ((string)(this["ChromeLocation"]));
            }
            set {
                this["ChromeLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2015")]
        public string CurrentDateString {
            get {
                return ((string)(this["CurrentDateString"]));
            }
            set {
                this["CurrentDateString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2016")]
        public string FutureDateToString {
            get {
                return ((string)(this["FutureDateToString"]));
            }
            set {
                this["FutureDateToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2016")]
        public string FutureDateFromString {
            get {
                return ((string)(this["FutureDateFromString"]));
            }
            set {
                this["FutureDateFromString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5FNRL189X2B074795")]
        public string VIN1QA {
            get {
                return ((string)(this["VIN1QA"]));
            }
            set {
                this["VIN1QA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1D4GP45R65B450999")]
        public string VIN2QA {
            get {
                return ((string)(this["VIN2QA"]));
            }
            set {
                this["VIN2QA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1JTHX63P2JT177903")]
        public string VIN1DEV {
            get {
                return ((string)(this["VIN1DEV"]));
            }
            set {
                this["VIN1DEV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\Screenshots\\")]
        public string ScreenshotPath {
            get {
                return ((string)(this["ScreenshotPath"]));
            }
            set {
                this["ScreenshotPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1J4NF4FB0AD501866")]
        public string VIN3QA {
            get {
                return ((string)(this["VIN3QA"]));
            }
            set {
                this["VIN3QA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Inside - Dashboard")]
        public string TitleDashboard {
            get {
                return ((string)(this["TitleDashboard"]));
            }
            set {
                this["TitleDashboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Inside - Delete Account")]
        public string TitleDelete {
            get {
                return ((string)(this["TitleDelete"]));
            }
            set {
                this["TitleDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Inside - Usage History")]
        public string TitleUsageHistory {
            get {
                return ((string)(this["TitleUsageHistory"]));
            }
            set {
                this["TitleUsageHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Inside - Purchase History")]
        public string TitlePurchaseHistory {
            get {
                return ((string)(this["TitlePurchaseHistory"]));
            }
            set {
                this["TitlePurchaseHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Inside - My Credit Cards")]
        public string TitleCreditCard {
            get {
                return ((string)(this["TitleCreditCard"]));
            }
            set {
                this["TitleCreditCard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Inside - Account Details")]
        public string TitleAccountDetails {
            get {
                return ((string)(this["TitleAccountDetails"]));
            }
            set {
                this["TitleAccountDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Inside - Faq")]
        public string TitleFAQ {
            get {
                return ((string)(this["TitleFAQ"]));
            }
            set {
                this["TitleFAQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Inside - Contact Us")]
        public string TitleContactUs {
            get {
                return ((string)(this["TitleContactUs"]));
            }
            set {
                this["TitleContactUs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Inside is a comprehensive global mobile communications service provided by C" +
            "ubic Telecom. The Data Inside service was developed to remove the complexity and" +
            " high-cost of mobile communications when you travel. Data Inside ensures that th" +
            "ese familiar tools can be used in the normal way while traveling without the fea" +
            "r of extortionate mobile bills. Data Inside delivers the following key benefits:" +
            "\r\n\r\nValue: You too can benefit from greatly reduced prices when you make access " +
            "the internet from anywhere in the world. The Data Inside service is borderless w" +
            "ith one low set of prices across 43 European countries. We also offer special bu" +
            "ndles which are tailored for your needs and offer even greater savings. We have " +
            "low cost plan bundles for surfing the internet. \r\n\r\nTransparency: No contracts, " +
            "no bills, no shocks. The Data Inside service is designed to take the mystery out" +
            " of mobile communications costs when you travel worldwide. There are no minimum " +
            "connection charges, no minimum daily bundles or multi-tiered prices. There are n" +
            "o hidden extra charges - Data Inside is a completely transparent service. Our st" +
            "raight forward low prices are easy to understand and our user friendly on line c" +
            "all records let you see exactly how much you are spending as you use the service" +
            ". You can check what you spend every day. You can be sure there will be no nasty" +
            " bills waiting for you when you get home.\r\n\r\nConvenience: The Data Inside servic" +
            "e is designed so that mobile internet works in the same familiar way when you tr" +
            "avel. No need to worry about special commands or new menus, you just surf the we" +
            "b as you would normally. When you register you are given a Data Inside wallet wh" +
            "ich stores your prepaid credit. You can easily check your balance, see your usag" +
            "e online call records, add credit and credit bundles to your account and set up " +
            "auto top-up so you never run out of credit.\r\n\r\nReliability: The Data Inside serv" +
            "ice is implemented on an advanced platform which has been built using world-clas" +
            "s 3G technologies and established 3G standards. The Data Inside SIM card connect" +
            "s seamlessly and reliably to the best quality 3G networks in 180+ countries worl" +
            "d-wide, ensuring the best call quality and the highest speeds when accessing the" +
            " internet.\r\n\r\nData Inside is a global service that is not confined to one countr" +
            "y or market. Getting started with Data Inside is straightforward. You simply reg" +
            "ister your account on the Data Inside web site before you travel and your initia" +
            "l credit can be ordered in-car or on-line via simple menus. Additional credit is" +
            " purchased both in-car or on-line as you require it.")]
        public string FAQ1 {
            get {
                return ((string)(this["FAQ1"]));
            }
            set {
                this["FAQ1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A range of great value local and international data plans can be purchased from a" +
            "s little as €8.99 per month. See our Rates page for further details.")]
        public string FAQ2 {
            get {
                return ((string)(this["FAQ2"]));
            }
            set {
                this["FAQ2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Inside can be used in the following destinations providing the correct bundl" +
            "e has been applied:")]
        public string FAQ3 {
            get {
                return ((string)(this["FAQ3"]));
            }
            set {
                this["FAQ3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Inside currently comes pre-installed in the new A4, A5, Q7, Q5, A3, Q1 (2016" +
            " models)")]
        public string FAQ4 {
            get {
                return ((string)(this["FAQ4"]));
            }
            set {
                this["FAQ4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You can register your Data Inside account by following the steps below:")]
        public string FAQ5 {
            get {
                return ((string)(this["FAQ5"]));
            }
            set {
                this["FAQ5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"There are three different types of account:
• Pending SIM owner: This user status suggests the user has registered as a SIM owner however has not made a purchase to complete this process. At this stage another user can register and become a pending SIM owner, SIM owner only become fully liable once a purchase is made. This will leave the pending SIM owner as a standard user.
• SIM owner: This user is the user legally responsible for the data usage across all accounts registered to the vehicle. A SIM owner can view all purchases made across all accounts and can view usage history. A SIM owner can also activate the feature “In-Car Top up” from their dashboard.
• Standard user: A standard user can view purchases made through their own account, view data usage and also purchase plans. They are unable to view purchases made on other accounts registered to the vehicle nor are they able to activate “In-Car Top up”.")]
        public string FAQ6 {
            get {
                return ((string)(this["FAQ6"]));
            }
            set {
                this["FAQ6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"This feature will be available through the Audi connect service ""Data plans"" of your vehicle providing the SIM owner of the vehicle has activated the “In-Car Top up” feature. All users in the vehicle can top up via the Audi connect service and all payment will be deducted from the payment card linked to the vehicle by the SIM owner. This card can be changed via the SIM owner’s account, by visiting the “Manage In-Car Top up” section on the dashboard and selecting an alternative saved card. If there is only one saved card on the account, another credit card will need to be saved before the current card can be changed. A purchase will need to be made in order to save any credit card. You can set a maximum top up limit per 7 days for In-Car Top ups.")]
        public string FAQ7 {
            get {
                return ((string)(this["FAQ7"]));
            }
            set {
                this["FAQ7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("To purchase a data plan please follow the steps below:")]
        public string FAQ8 {
            get {
                return ((string)(this["FAQ8"]));
            }
            set {
                this["FAQ8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"You can choose to purchase a range of local or European plans depending on your needs. Local bundles are available for use in local countries only or Roaming bundles can be purchased which will allow activity in selected countries. See our Rates page for a list of data plans and country coverage.")]
        public string FAQ9 {
            get {
                return ((string)(this["FAQ9"]));
            }
            set {
                this["FAQ9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Depending on the bundle being purchased, the expiration can be 7 days, 1 month or" +
            " 365 days. There is no carry-over of unused data from period to period.")]
        public string FAQ10 {
            get {
                return ((string)(this["FAQ10"]));
            }
            set {
                this["FAQ10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Depending on the bundle being purchased, the expiration can be 7 days, 1 month or" +
            " 365 days or until the allocated data is exhausted.")]
        public string FAQ11 {
            get {
                return ((string)(this["FAQ11"]));
            }
            set {
                this["FAQ11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Pending plans are plans that have been purchased but are not currently being used. They become active when the current plan becomes exhausted or expires or when the vehicle travels to a different country. Should two local plans be added to the same vehicle, the expiration of the second local bundle will not begin until the first has been exhausted or expired. Should a local bundle and a European Plan (Small European or Large European) be added to the same vehicle, the local bundle will activate when using data in the local country, however once the vehicle travels to a roaming country, the roaming bundle will activate.")]
        public string FAQ12 {
            get {
                return ((string)(this["FAQ12"]));
            }
            set {
                this["FAQ12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CubicTelecom will not charge you for a failed transaction. There may be an author" +
            "ization request that appears on your bank statement, however this will not be co" +
            "mpleted and the money remains in your account. The authorization will be removed" +
            " by your bank")]
        public string FAQ13 {
            get {
                return ((string)(this["FAQ13"]));
            }
            set {
                this["FAQ13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("We currently accept:")]
        public string FAQ14 {
            get {
                return ((string)(this["FAQ14"]));
            }
            set {
                this["FAQ14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"If you are SIM owner for a car, the currency used will be the currency applied when topping up that car (which is the currency used in the country you chose at registration). If you are a standard user for a car the currency used when topping up that car will be the currency used in the SIM owner's country of registration.")]
        public string FAQ15 {
            get {
                return ((string)(this["FAQ15"]));
            }
            set {
                this["FAQ15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This can be done by visiting your customer account, selecting the account details" +
            " option and then selecting “Credit Card Management” option. From here you can se" +
            "lect your favourite card to be used or delete any saved credit cards on the acco" +
            "unt.")]
        public string FAQ16 {
            get {
                return ((string)(this["FAQ16"]));
            }
            set {
                this["FAQ16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You can log into your account using your username and password on www.datainside." +
            "com. Once logged in, you can purchase data plans, check your usage in real time " +
            "and manage your personal information.")]
        public string FAQ17 {
            get {
                return ((string)(this["FAQ17"]));
            }
            set {
                this["FAQ17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"At each purchase you will be asked if you would like to use a previously saved credit card or if you would like to use a new one. You have the option to save your last used credit card details. To remove a credit card from your account please visit the “Credit Card Management” section on your customer account.")]
        public string FAQ18 {
            get {
                return ((string)(this["FAQ18"]));
            }
            set {
                this["FAQ18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("In exceptional circumstances, such as a country relocation, you may change the ho" +
            "me country where you would like data plans to be available for purchase. This ca" +
            "n be done by contacting us at info@datainside.com")]
        public string FAQ19 {
            get {
                return ((string)(this["FAQ19"]));
            }
            set {
                this["FAQ19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"A customer can delete their account at any time by visiting their customer account, selecting the Account Details and choosing the “Delete Account” option. If the account being deleted is the SIM owner account this will prevent all other users from topping up and will deactivate in car top up. Any standard user associated with this account can register as SIM owner when accessing their own account at this stage and can re-instate these privileges and features. Deleting the Liable account can also be done from the MMI of the vehicle by selecting the “Data plans” option from the Audi connect menu and selecting the ""Delete SIM owner"" option.")]
        public string FAQ20 {
            get {
                return ((string)(this["FAQ20"]));
            }
            set {
                this["FAQ20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("For full details and support on using your MMI please contact myaudi.com")]
        public string FAQ21 {
            get {
                return ((string)(this["FAQ21"]));
            }
            set {
                this["FAQ21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data plans are live as soon as they are purchased. Subsequent plans purchased for the same geographical region will be queued and marked as ‘pending’ until the current plan is fully consumed, or expires. A pending plan will then become the current plan, with no noticeable changeover to the user.
If a user has two or more plans for different geographical regions, these plans will run concurrently and depending on the users location, the appropriate plan will be marked as current and consumed from.
For example, if a user, living in Germany, has a local German plan and a European Border plan, both will be live but whilst in Germany, data will be consumed from the German plan and the European Border plan will be deactivated. If the user crosses the border to Austria, data will now be consumed from the European Border plan and the German plan will now be deactivated.")]
        public string FAQ22 {
            get {
                return ((string)(this["FAQ22"]));
            }
            set {
                this["FAQ22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Thank You
We appreciate your taking the time to contact us.
Your message was successfully sent to the Cubic Telecom support team. If your message requires a response, we will get back to you as soon as we can. We do our best to answer emails within 1-2 business days (Monday-Friday).
Occasionally we receive a very large number of messages, and your response may take a little longer. If this occurs, we appreciate your patience, and we assure you that you will receive a response.
Have A Great Day,
Cubic Telecom Support Team")]
        public string ContactThankYou {
            get {
                return ((string)(this["ContactThankYou"]));
            }
            set {
                this["ContactThankYou"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You will receive an email from us with instructions for resetting your password.")]
        public string ForgotPWMailSent {
            get {
                return ((string)(this["ForgotPWMailSent"]));
            }
            set {
                this["ForgotPWMailSent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thank You for registering with Data Inside. Before you can start using our servic" +
            "e you need to confirm your email. We have sent an email to the address provided " +
            "during your registration, please follow the steps in your email.")]
        public string CreateAccountConfirmed {
            get {
                return ((string)(this["CreateAccountConfirmed"]));
            }
            set {
                this["CreateAccountConfirmed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=cubicqaserver.cloudapp.net;Database=dbMAXroamResellersV12;User Id=cubic-do" +
            "rgan;Password=pass123-;")]
        public string DBConnectionStringQa {
            get {
                return ((string)(this["DBConnectionStringQa"]));
            }
            set {
                this["DBConnectionStringQa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2.1.28")]
        public string SoftwareVersion {
            get {
                return ((string)(this["SoftwareVersion"]));
            }
            set {
                this["SoftwareVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visa **** **** **** 0281 expiring on 01/19")]
        public string CurrentCreditCardString {
            get {
                return ((string)(this["CurrentCreditCardString"]));
            }
            set {
                this["CurrentCreditCardString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You don\'t currently have any stored credit cards.")]
        public string NoCardString {
            get {
                return ((string)(this["NoCardString"]));
            }
            set {
                this["NoCardString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("standard@testuser.com")]
        public string StandardUser {
            get {
                return ((string)(this["StandardUser"]));
            }
            set {
                this["StandardUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Inside - Vehicle - Add")]
        public string TitleAddVin {
            get {
                return ((string)(this["TitleAddVin"]));
            }
            set {
                this["TitleAddVin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Inside - Home")]
        public string TitleHome {
            get {
                return ((string)(this["TitleHome"]));
            }
            set {
                this["TitleHome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Account/ActivateAccount?accounttoken=")]
        public string ActivateAccountSubURL {
            get {
                return ((string)(this["ActivateAccountSubURL"]));
            }
            set {
                this["ActivateAccountSubURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The date must be before today")]
        public string FromDateErrorPurchaseHistory {
            get {
                return ((string)(this["FromDateErrorPurchaseHistory"]));
            }
            set {
                this["FromDateErrorPurchaseHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The date must be after the from date and before today.")]
        public string ToDateErrorPurchaseHistory {
            get {
                return ((string)(this["ToDateErrorPurchaseHistory"]));
            }
            set {
                this["ToDateErrorPurchaseHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The date must be before today")]
        public string FromDateErrorUsageHistory {
            get {
                return ((string)(this["FromDateErrorUsageHistory"]));
            }
            set {
                this["FromDateErrorUsageHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The date must be after the from date and before today.")]
        public string ToDateErrorUsageHistory {
            get {
                return ((string)(this["ToDateErrorUsageHistory"]));
            }
            set {
                this["ToDateErrorUsageHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@davidocubic.33mail.com")]
        public string DisposableMail {
            get {
                return ((string)(this["DisposableMail"]));
            }
            set {
                this["DisposableMail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int NewMailCounter {
            get {
                return ((int)(this["NewMailCounter"]));
            }
            set {
                this["NewMailCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Password Successfully Changed\r\nYour new Data Inside password has been set. You ca" +
            "n now access your account, top-up or view your usage history.")]
        public string PasswordChangedSuccessMessage {
            get {
                return ((string)(this["PasswordChangedSuccessMessage"]));
            }
            set {
                this["PasswordChangedSuccessMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Account/ResetPassword?resetToken=")]
        public string ResetPasswordSubURL {
            get {
                return ((string)(this["ResetPasswordSubURL"]));
            }
            set {
                this["ResetPasswordSubURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Your account has been updated successfully. Use the button below to go back to th" +
            "e dashboard.")]
        public string AccountUpdatedSuccessMessage {
            get {
                return ((string)(this["AccountUpdatedSuccessMessage"]));
            }
            set {
                this["AccountUpdatedSuccessMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5FNRL189X2B074795")]
        public string CurrentVIN {
            get {
                return ((string)(this["CurrentVIN"]));
            }
            set {
                this["CurrentVIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1D4GP45R65B450999")]
        public string AddedVIN {
            get {
                return ((string)(this["AddedVIN"]));
            }
            set {
                this["AddedVIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thank you for purchasing the Germany 1 Day 50MB plan.")]
        public string PlanPurchaseSuccessLocal {
            get {
                return ((string)(this["PlanPurchaseSuccessLocal"]));
            }
            set {
                this["PlanPurchaseSuccessLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cubic1234!")]
        public string AltPassword {
            get {
                return ((string)(this["AltPassword"]));
            }
            set {
                this["AltPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Your password has been updated successfully. Use the button below to go back to t" +
            "he dashboard.")]
        public string PasswordUpdateSuccess {
            get {
                return ((string)(this["PasswordUpdateSuccess"]));
            }
            set {
                this["PasswordUpdateSuccess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name is required")]
        public string ContactNameError {
            get {
                return ((string)(this["ContactNameError"]));
            }
            set {
                this["ContactNameError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Email is required")]
        public string ContactEmailError {
            get {
                return ((string)(this["ContactEmailError"]));
            }
            set {
                this["ContactEmailError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Phone number is required")]
        public string ContactPhoneError {
            get {
                return ((string)(this["ContactPhoneError"]));
            }
            set {
                this["ContactPhoneError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Message is required")]
        public string ContactMessageError {
            get {
                return ((string)(this["ContactMessageError"]));
            }
            set {
                this["ContactMessageError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chrome")]
        public string Driver {
            get {
                return ((string)(this["Driver"]));
            }
            set {
                this["Driver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The vehicle identification number specified has already been added to the dashboa" +
            "rd.\r\nPlease verify that the number is correct and try again.\r\n×")]
        public string RegisterdCarAlert {
            get {
                return ((string)(this["RegisterdCarAlert"]));
            }
            set {
                this["RegisterdCarAlert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vehicle Identification Number field is required")]
        public string AddEmptyVINMessage {
            get {
                return ((string)(this["AddEmptyVINMessage"]));
            }
            set {
                this["AddEmptyVINMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The VIN number entered was not found, please retry or contact support if you cont" +
            "inue to see this message.")]
        public string InvalidVINErrorMessage {
            get {
                return ((string)(this["InvalidVINErrorMessage"]));
            }
            set {
                this["InvalidVINErrorMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The credit card you are deleting is being used for in car top up. You need to tur" +
            "n off in car top up for the following vehicles before deleting this credit card:" +
            "\r\n5FNRL189X2B074795")]
        public string DeleteCardSponsorWarning {
            get {
                return ((string)(this["DeleteCardSponsorWarning"]));
            }
            set {
                this["DeleteCardSponsorWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=auto-uat-web-01.cloudapp.net;Database=dbMAXroamResellersV12;User Id=cubic-" +
            "dorgan;Password=pass123-;")]
        public string DBConnectionStringUAT {
            get {
                return ((string)(this["DBConnectionStringUAT"]));
            }
            set {
                this["DBConnectionStringUAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\IEDriver")]
        public string IELocation {
            get {
                return ((string)(this["IELocation"]));
            }
            set {
                this["IELocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The Name field is required.")]
        public string CreditCardEmptyNameError {
            get {
                return ((string)(this["CreditCardEmptyNameError"]));
            }
            set {
                this["CreditCardEmptyNameError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The Card Number field is required.")]
        public string CreditCardEmptyNumberError {
            get {
                return ((string)(this["CreditCardEmptyNumberError"]));
            }
            set {
                this["CreditCardEmptyNumberError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The CVV field is required.")]
        public string CreditCardEmptyCVVError {
            get {
                return ((string)(this["CreditCardEmptyCVVError"]));
            }
            set {
                this["CreditCardEmptyCVVError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The value is not a valid credit card number.")]
        public string CreditCardInvalidError {
            get {
                return ((string)(this["CreditCardInvalidError"]));
            }
            set {
                this["CreditCardInvalidError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The credit card is out of date.")]
        public string CreditCardExpireMonthError {
            get {
                return ((string)(this["CreditCardExpireMonthError"]));
            }
            set {
                this["CreditCardExpireMonthError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The field CVV must be a string with a minimum length of 3 and a maximum length of" +
            " 4.")]
        public string CreditCardInvalidCVVError {
            get {
                return ((string)(this["CreditCardInvalidCVVError"]));
            }
            set {
                this["CreditCardInvalidCVVError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The Name field requires at least 2 words")]
        public string CreditCardInvalidNameError {
            get {
                return ((string)(this["CreditCardInvalidNameError"]));
            }
            set {
                this["CreditCardInvalidNameError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Germany")]
        public string AccountLocale {
            get {
                return ((string)(this["AccountLocale"]));
            }
            set {
                this["AccountLocale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("© 2015. Cubic Telecom Ltd. All rights reserved")]
        public string FooterCopyrightText {
            get {
                return ((string)(this["FooterCopyrightText"]));
            }
            set {
                this["FooterCopyrightText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thank you for purchasing the EU Roaming 1 Day 50MB plan.")]
        public string PlanPurchaseSuccessEuropeRoaming {
            get {
                return ((string)(this["PlanPurchaseSuccessEuropeRoaming"]));
            }
            set {
                this["PlanPurchaseSuccessEuropeRoaming"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thank you for purchasing the Europe Border 1 Day 50MB plan.")]
        public string PlanPurchaseSuccessEuropeBorder {
            get {
                return ((string)(this["PlanPurchaseSuccessEuropeBorder"]));
            }
            set {
                this["PlanPurchaseSuccessEuropeBorder"] = value;
            }
        }
    }
}
